// AWS Access Key (VALID FORMAT – fake)
const AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE";

// AWS Secret Key (40 chars – valid pattern)
const AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";

// PEM-style private key (valid entropy)
const AWS_SESSION_TOKEN = `
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAz9x4H9x4H9x4H9x4H9x4H9x4H9x4H9x4
Y3G7v9Y1N9y8yJzXyE9sZ8zqQ4Rz8A1nK8s8Lz8PZ9Z8x7x
x9QIDAQABAoIBAQCtExamplePrivateKeyMaterial123456
-----END RSA PRIVATE KEY-----
`;
